### ISSUE TITLE
Is judge mixing up improvements and regressions?

### ISSUE THREAD

**Issue by davidanthoff** [JuliaCI/PkgBenchmark.jl#11]
I start out with this code:
````julia
function foo(n)
    res = 0
    for i=1:n
        res += i
    end
    return res
end

@benchgroup "stupid-test" begin
    @bench "basic" foo(1_000_000)
end
````
I commit this in my branch and then run ``benchmarkpkg``. Next I change this code to
````julia
function foo(n)
    res = 0
    for i=1:n
        res += i^2
    end
    return res
end

@benchgroup "stupid-test" begin
    @bench "basic" foo(1_000_000_000)
end
````
I then run ``showall(judge("Packagename", "branchname"))``. I would expect this to show me a regression, i.e. an increase in time. But instead it shows:
````
"stupid-test" => 1-element BenchmarkTools.BenchmarkGroup:
        tags: []
        "basic" => TrialJudgement(-10.00% => improvement)
````
I would have expected exactly the opposite, i.e. a positive percentage change because runtime has increased and as a judgment that this is a regression. Am I missing something basic?

**Comment by nalimilan** [comment]
I've run into the same issue. I think the documentation is indeed backwards.

@shashi Can you confirm this? Then the fix is easy to make. :-)

**Comment by davidanthoff** [comment]
@shashi Is this fixed now? If so, could you tag a new release?

**Comment by shashi** [comment]
It's partially fixed. I need to wrap `git stash` from LibGit2 to actually make it work for the current state of the repo. It works if you are comparing a clean commit with another clean commit.

**Comment by Evizero** [comment]
Seems to work correctly for me. (dirty vs clean)

**Comment by KristofferC** [comment]
The code here gets compiled to not run the loop at all. 

```
julia> @btime foo(1000)
  3.267 ns (0 allocations: 0 bytes)
500500

julia> @btime foo(100000)
  3.558 ns (0 allocations: 0 bytes)
5000050000
```

Modifying the benchmark so it works (this is on a branch with some other changes but anyway):

```
julia> showall(PkgBenchmark.benchmarkgroup(judge("Test", PR_fast, baseline_slow)))
1-element BenchmarkTools.BenchmarkGroup:
  tags: []
  "stupid-test" => 1-element BenchmarkTools.BenchmarkGroup:
	  tags: []
	  "basic" => TrialJudgement(-99.11% => improvement)
```
